import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@nextcss/reset";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer.server";
import FooterDataFetcher from "./components/Footer.server";

import ReactQueryProvider from "./ReactQueryProvider";
import Link from "next/link";
import CreateBook from "./components/CreateBook";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <Link href='/'>Trang chủ</Link>
          <br/>
          <Link href='/dang-nhap'>Đăng nhập</Link>
          <br/>
          <CreateBook/>
          {children}
          {/* <FooterDataFetcher /> */}
        </body>
      </html>
    </ReactQueryProvider>
  );
}
